version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./NGINX
    volumes:
      - ./NGINX/logs:/var/log/nginx
    ports:
      - '80:80'

  web-front:
    build:
      context: ./WEB
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./WEB/html:usr/local/apache2/htdocs
    ports:
      - '8080:80'